# Generated by Django 5.2.11 on 2026-02-18 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='users.examtype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Exam',
                'verbose_name_plural': 'User Exams',
                'db_table': 'users_user_exam',
            },
        ),
    ]
